server:
  port: 8001
spring:
  application:
    name: temperature-microservice
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/